const MARKET_BASED_TOKENS = ['EOS', 'USD'];
const MARKET_RATE_FETCHING_INTERVAL = 10000;
const MAX_SRC_AMOUNT_BY_EOS = 20;
const MIN_CONVERSION_RATE = "0.000001";
const SCATTER_ERROR_TYPE = 'scatter';

export { MARKET_BASED_TOKENS, MIN_CONVERSION_RATE, MAX_SRC_AMOUNT_BY_EOS, SCATTER_ERROR_TYPE, MARKET_RATE_FETCHING_INTERVAL }
