const MARKET_BASED_TOKENS = ['EOS', 'USD'];
const MAX_DEST_AMOUNT = 1000000000;
const MIN_CONVERSION_RATE = "0.000001";
const SCATTER_ERROR_TYPE = 'scatter';

export { MARKET_BASED_TOKENS, MAX_DEST_AMOUNT, MIN_CONVERSION_RATE, SCATTER_ERROR_TYPE }
